[isolate-panel]
enabled = true
port = 8080,443,8443
filter = isolate-panel
logpath = /var/log/isolate-panel/isolate-panel.log
maxretry = 5
findtime = 15m
bantime = 1h
backend = auto
banaction = iptables-multiport
action = %(action_)s
